version: "3.1"
services:

  kiara:
    build: https://github.com/Nekorooni/Kiara.git
    container_name: kiara
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  # Storage
  db:
    image: mysql:5.7.22
    container_name: db
    volumes:
      - ./db.cnf:/etc/mysql/conf.d/kiara.cnf
      - ./db-init/:/docker-entrypoint-initdb.d/
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    restart: always

  redis:
    image: redis:4.0.9-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-store:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    restart: always
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always
  
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
 
  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    
  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    environment:
      - REDIS_ADDR=redis://redis
    command:
      - '-check-single-keys=${REDIS_METRICS_SINGLE_KEYS:-none}'
    restart: always
    

volumes:
  db-store: {}
  redis-store: {}
  prometheus_data: {}
  grafana_data: {}
